[package]
name = "osu-native"
version = "0.1.0"
edition = "2024"

[dependencies]
libosu-native-sys = { path = "../libosu-native-sys" }
rosu-mods = { git = "https://github.com/MaxOhn/rosu-mods", branch = "simple-settings", features = ["serde"] }
serde_json = "1.0.142"
thiserror = "2.0.14"
